# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import yaml
from datetime import datetime
from pathlib import Path

# Sphinx may be launched from the repository root (or another working
# directory), so resolve local helper modules relative to this file.
source_dir = Path(__file__).resolve().parent
sys.path.insert(0, str(source_dir))

from utils.language_support import (
    alternate_docname,
    detect_languages,
    document_language,
    language_output_docname,
    language_root_docname,
    language_switch_enabled,
    relative_doc_url,
    select_default_language,
)
from utils.pdf_formatting import normalize_latex_heading_numbers

# 加载配置文件
def load_config():
    """加载配置文件"""
    config_path = os.path.join(os.path.dirname(__file__), 'config.yaml')
    if os.path.exists(config_path):
        with open(config_path, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)
    return {}

config = load_config()
project_config = config.get('project', {})
sphinx_config = config.get('sphinx', {})
repository_config = config.get('repository', {})
generation_config = config.get('generation', {})
giscus_config = config.get('giscus', {})
configured_build_languages = tuple(
    language.strip()
    for language in os.environ.get("DOCS_AVAILABLE_LANGUAGES", "").split(",")
    if language.strip() in {"zh", "en"}
)
available_languages = configured_build_languages or detect_languages(
    source_dir, generation_config
)
default_language = select_default_language(
    available_languages, generation_config
)

# -- Project information -----------------------------------------------------

project = project_config.get('name', 'SDK_Docs')
copyright = project_config.get('copyright', '2025, apache')
author = project_config.get('author', 'unknown')

# The full version, including alpha/beta/rc tags
release = project_config.get('version', '0.0.1')


def get_configured_root_doc():
    """返回同步后的默认页面；无效配置使用生成的语言首页。"""
    return language_root_docname(
        source_dir, generation_config, default_language
    )


# 环境变量仍可覆盖 config.yaml，供特殊构建任务使用。
master_doc = os.environ.get('SPHINX_MASTER_DOC', get_configured_root_doc())

# 如果通过命令行参数指定了master_doc，则使用命令行参数的值
# 这需要在构建脚本中通过环境变量传递
if 'SPHINX_MASTER_DOC_OVERRIDE' in os.environ:
    master_doc = os.environ['SPHINX_MASTER_DOC_OVERRIDE']
root_doc = master_doc

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = sphinx_config.get('extensions', ['myst_parser'])

source_suffix = sphinx_config.get('source_suffix', {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
})

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
# 优先使用环境变量，然后使用配置文件，最后使用默认值
default_sphinx_language = 'zh_CN' if default_language == 'zh' else 'en'
language = os.environ.get('SPHINX_LANGUAGE', default_sphinx_language)
active_build_language = (
    'zh' if str(language).lower().startswith('zh') else 'en'
)

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
# 基础排除模式
base_exclude_patterns = [
    'MIGRATION_GUIDE.md',
    'OPTIMIZATION_SUMMARY.md',
    'README_NEW_BUILD_SYSTEM.md',
    'requirements.txt',
    'utils/',
    'config_templates/**',
    '_templates/',
    '_static/',
    '_build/',
    '.doc_generator_manifest.json',
]

# 根据环境变量设置文档排除模式
exclude_patterns = base_exclude_patterns.copy()
if 'SPHINX_EXCLUDE_PATTERNS' in os.environ:
    env_exclude_patterns = os.environ['SPHINX_EXCLUDE_PATTERNS'].split(',')
    env_exclude_patterns = [pattern.strip() for pattern in env_exclude_patterns if pattern.strip()]
    exclude_patterns.extend(env_exclude_patterns)

# 调试信息
print(f"DEBUG: master_doc = {master_doc}")
print(f"DEBUG: language = {language}")
print(f"DEBUG: exclude_patterns = {exclude_patterns}")

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation
# for a list of builtin themes.
#
html_theme = sphinx_config.get('theme', 'sphinx_rtd_theme')
html_title = project_config.get('title', project)

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# -- Options for internationalization ----------------------------------------

# 多语言支持配置
# locale_dirs = ['../locale/']
# gettext_compact = False

# -- MyST Parser configuration ----------------------------------------------

myst_enable_extensions = sphinx_config.get('myst_extensions', [
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
    "html_admonition",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
])

# MyST图片配置
myst_gfm_only = False
myst_heading_anchors = 0

# 配置图片处理
myst_all_links_external = False
myst_url_schemes = ('http', 'https', 'mailto', 'ftp')

# 图片路径配置
html_extra_path = []
html_css_files = ['version_menu.css', 'custom.css', 'pdf_button.css', 'edit_button.css', 'language_switch.css', 'dark_mode.css']
html_js_files = ['version_menu.js', 'download_pdf.js', 'version_info.js', 'edit_on_github.js', 'language_switch.js']

# 配置图片路径处理
html_favicon = None

# 配置文档结构
html_show_sourcelink = False
html_show_sphinx = False
html_show_copyright = True

# 配置导航
html_theme_options = {
    'navigation_depth': 4,
    'titles_only': False,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'includehidden': True,
}

# 配置文档结构
html_use_index = True
html_split_index = False
html_copy_source = False

# 配置导航结构
html_sidebars = {
    '**': [
        'globaltoc.html',
        'relations.html',
        'sourcelink.html',
        'searchbox.html',
    ]
}

# 配置toctree选项
html_use_index = True
html_split_index = False
html_copy_source = False

# 检测构建环境并配置URL
import os
is_github_actions = os.environ.get('GITHUB_ACTIONS') == 'true'

if is_github_actions:
    # GitHub Pages环境：使用相对URL
    html_use_relative_urls = True
    html_baseurl = ""
else:
    # 本地构建环境：使用相对URL，但禁用canonical链接
    html_use_relative_urls = True
    html_baseurl = ""
    # 禁用canonical链接以避免错误的绝对路径
    html_show_sourcelink = False


# 传递编辑基础 URL 给模板/前端脚本
def derive_edit_base_url():
    # 优先使用 config.yaml 显式配置
    explicit = (repository_config.get('edit_base_url', '') or '').strip()
    if explicit:
        return explicit.rstrip('/') + '/'

    # 其后尝试从 GitHub Actions 环境变量推断（owner/repo）
    gh_repo = os.environ.get('GITHUB_REPOSITORY', '').strip()  # e.g. owner/name
    if gh_repo and '/' in gh_repo:
        return f"https://github.com/{gh_repo}/edit/"

    # 再其次，从 git remote.origin.url 推断
    try:
        import subprocess
        origin = subprocess.run(['git', 'config', '--get', 'remote.origin.url'],
                                capture_output=True, text=True, check=True).stdout.strip()
        if origin:
            if origin.startswith('git@') and 'github.com:' in origin:
                # git@github.com:owner/repo.git
                repo_path = origin.split('github.com:')[-1]
                repo_path = repo_path[:-4] if repo_path.endswith('.git') else repo_path
                return f"https://github.com/{repo_path}/edit/"
            if origin.startswith('https://') and 'github.com' in origin:
                # https://github.com/owner/repo.git
                repo_path = origin.split('github.com/')[-1]
                repo_path = repo_path[:-4] if repo_path.endswith('.git') else repo_path
                return f"https://github.com/{repo_path}/edit/"
    except Exception:
        pass

    # 最后兜底：使用 repository.name（无法确定 owner，仅供部分场景）
    repo_name = (repository_config.get('name', '') or '').strip()
    if repo_name:
        return f"https://github.com/{repo_name}/edit/"
    return ''

html_context = {
    'edit_base_url': derive_edit_base_url(),
    # 将 giscus 配置传入模板；若未启用或缺关键字段，模板中将忽略
    'giscus': giscus_config or {},
}


def _source_doc_exists(docname):
    return any(
        (source_dir / f"{docname}{suffix}").is_file()
        for suffix in source_suffix
    )


def _language_root_doc(language_code):
    return language_root_docname(
        source_dir, generation_config, language_code
    )


def add_language_page_context(app, pagename, templatename, context, doctree):
    """Expose an exact per-page language target to the frontend switcher."""
    del app, templatename, doctree
    if not language_switch_enabled(available_languages):
        context['docs_language'] = {
            'enabled': False,
            'available': list(available_languages),
            'current': default_language,
        }
        return

    current_language = (
        document_language(Path(pagename))
        if _source_doc_exists(pagename)
        else active_build_language
    )
    target_language = 'en' if current_language == 'zh' else 'zh'
    target_docname = alternate_docname(pagename, target_language)
    if not _source_doc_exists(target_docname):
        target_docname = _language_root_doc(target_language)
    target_output_docname = language_output_docname(
        target_docname, target_language, default_language
    )
    context['docs_language'] = {
        'enabled': True,
        'available': list(available_languages),
        'current': current_language,
        'target_language': target_language,
        'target_docname': target_docname,
        'target_url': relative_doc_url(pagename, target_output_docname),
    }


def setup(app):
    app.connect('html-page-context', add_language_page_context)
    app.connect('doctree-resolved', normalize_latex_heading_numbers)
"""
LaTeX / PDF 构建配置
"""
# --- 国际 Word 排版补丁 (start) ---
# 使用 standard 表格样式（不依赖 booktabs），规避 colortbl/booktabs 在 xeCJK 下的 \\everycr 递归
latex_table_style = ['standard']


def _latex_escape(value):
    """Escape config text embedded directly in the PDF title page."""
    replacements = {
        '\\': r'\textbackslash{}',
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
    }
    return ''.join(replacements.get(char, char) for char in str(value or ''))


pdf_is_chinese = str(language).lower().startswith('zh')
pdf_style = os.environ.get(
    'PDF_STYLE', generation_config.get('pdf_style', 'web')
).strip().lower()
pdf_thesis_style = pdf_style in {'thesis', 'graduate', 'academic'}
pdf_cover_title = os.environ.get(
    'PDF_COVER_TITLE', str(project).replace('_', ' ')
)
pdf_header_title = str(project).replace('_', ' ')
pdf_cover_type = os.environ.get(
    'PDF_COVER_TYPE',
    '开发文档' if pdf_is_chinese else 'Technical Documentation',
)
pdf_cover_description = os.environ.get(
    'PDF_COVER_DESCRIPTION',
    project_config.get('description', '')
    if pdf_is_chinese
    else project_config.get('description_en', '') or project_config.get('description', ''),
)
pdf_cover_date = datetime.now().strftime('%Y-%m-%d')
pdf_version_label = '文档版本' if pdf_is_chinese else 'Document version'
pdf_date_label = '更新时间' if pdf_is_chinese else 'Last updated'
pdf_contents_title = '目录' if pdf_is_chinese else 'Contents'

pdf_fonts = generation_config.get('pdf_fonts', {}) or {}
pdf_font_latin = str(pdf_fonts.get('latin', 'TeX Gyre Termes'))
pdf_font_cjk_body = str(
    pdf_fonts.get('cjk_body', 'FandolSong-Regular.otf')
)
pdf_font_cjk_heading = str(
    pdf_fonts.get('cjk_heading', 'FandolHei-Regular.otf')
)
pdf_font_cjk_emphasis = str(
    pdf_fonts.get('cjk_emphasis', 'FandolKai-Regular.otf')
)
pdf_font_code = str(pdf_fonts.get('code', 'Source Code Pro'))

pdf_cover_page = rf'''
\begin{{titlepage}}
\newgeometry{{top=2.2cm,bottom=2.0cm,left=2.4cm,right=2.4cm}}
\thispagestyle{{pdfcover}}
\begin{{flushleft}}
\vspace*{{0.6cm}}
{{\color{{coverblue}}\rule{{2.4cm}}{{4pt}}\par}}
\vspace{{0.9cm}}
{{\sffamily\small\bfseries\color{{covermuted}} REALTHREAD \enspace/\enspace TECHNICAL DOCUMENTATION\par}}
\vspace{{2.0cm}}
{{\sffamily\bfseries\fontsize{{32}}{{39}}\selectfont\color{{coverink}} {_latex_escape(pdf_cover_title)}\par}}
\vspace{{0.45cm}}
{{\sffamily\fontsize{{19}}{{25}}\selectfont\color{{coverblue}} {_latex_escape(pdf_cover_type)}\par}}
\vspace{{1.35cm}}
\begin{{minipage}}{{0.84\textwidth}}
{{\sffamily\large\color{{covermuted}} {_latex_escape(pdf_cover_description)}\par}}
\end{{minipage}}
\vfill
{{\color{{coverline}}\rule{{\textwidth}}{{0.8pt}}\par}}
\vspace{{0.65cm}}
{{\sffamily\small\color{{covermuted}} {_latex_escape(pdf_version_label)}\hspace{{1.2em}}{{\color{{coverink}}\bfseries {_latex_escape(release)}}}\par}}
\vspace{{0.20cm}}
{{\sffamily\small\color{{covermuted}} {_latex_escape(pdf_date_label)}\hspace{{1.2em}}{{\color{{coverink}} {_latex_escape(pdf_cover_date)}}}\par}}
\vspace{{1.0cm}}
{{\sffamily\footnotesize\color{{covermuted}} {_latex_escape(copyright)}\par}}
\end{{flushleft}}
\end{{titlepage}}
% Restore the body geometry after the titlepage environment has finished.
% Restoring inside titlepage can leave its enlarged text height on the first
% contents page, pushing the roman page number below the paper edge.
\restoregeometry
\clearpage
'''

latex_documents = [
    # (source start file, target name, title, author, documentclass [options])
    # manual 使用独立标题页，并让每篇正文成为清晰的章级结构。
    (master_doc, 'sdk-docs.tex', _latex_escape(pdf_cover_title), _latex_escape(author), 'manual'),
]

latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '11pt',
    'extraclassoptions': 'oneside,openany',
    # Sphinx's XeLaTeX default injects tgtermes/tgheros, which are optional
    # LaTeX packages and are not needed when fontspec selects our fonts below.
    'fontpkg': '',
    # PDF 目录保留三层：分类 README 标题、文档标题、正文章节。
    # 文档标题由 latex_toplevel_sectioning 设为 section 后处于第二层。
    'tocdepth': r'\setcounter{tocdepth}{2}',
    'maketitle': pdf_cover_page,
    'tableofcontents': rf'''
\clearpage
\renewcommand{{\contentsname}}{{{_latex_escape(pdf_contents_title)}}}
\pagestyle{{pdfnormal}}
\thispagestyle{{pdfnormal}}
\begin{{singlespace}}
\small
\sphinxtableofcontents
\end{{singlespace}}
\clearpage
''',
    'hyperref': r'''
\definecolor{wordlinkblue}{RGB}{5,99,193}
\usepackage[
  colorlinks=true,
  breaklinks=true,
  linkcolor=wordlinkblue,
  citecolor=wordlinkblue,
  urlcolor=wordlinkblue,
  filecolor=wordlinkblue,
  menucolor=wordlinkblue,
  pdfborder={0 0 0},
  bookmarks=true,
  bookmarksnumbered=true,
  bookmarksdepth=2,
  bookmarksopen=true,
  bookmarksopenlevel=1,
  pdfpagemode=UseOutlines,
  pdfstartview=FitH
]{hyperref}
\usepackage{hypcap}
\urlstyle{same}
''',
    'preamble': r'''
% =========================================================================
%  国际 Word 编码风格排版（贴近 Microsoft Word 国际默认）
% =========================================================================
% geometry 已被 sphinxoptionsgeometry.sty 加载；用 \geometry 重设 Word 默认边距
\geometry{a4paper, top=2.54cm, bottom=2.54cm, left=2.54cm, right=2.54cm,
          headheight=14pt, footskip=24pt, includehead=true, includefoot=true}

% microtype 对变字重 CJK 字体触发递归（input stack overflow），对中文正文禁用
% \usepackage{microtype}     % 禁用以避免 CJK tabulary 递归
\usepackage{setspace}      % 行距控制
\usepackage{xeCJK}         % CJK 字体支持
\usepackage{indentfirst}   % 段落首行缩进

% tabulary 在 xeCJK + 复杂表格时触发 \the\everycr 递归（input stack overflow）。
% 生成器将其改写为固定版心宽度的 tabularx，以下列类型负责自动换行与对齐。
\usepackage{tabularx}
\usepackage{array}
\newcolumntype{Y}{>{\raggedright\arraybackslash}X}
\newcolumntype{Z}{>{\centering\arraybackslash}X}
\newcolumntype{Q}{>{\raggedleft\arraybackslash}X}
% 表格统一使用标准可伸缩列，保证外框始终贴合版心宽度。
% 内容通过 X 列自动换行，不改变正文文字大小，也不引入自定义权重边界。
\usepackage{xcolor}        % 颜色支持
\definecolor{coverblue}{RGB}{0, 91, 150}
\definecolor{coverink}{RGB}{26, 39, 52}
\definecolor{covermuted}{RGB}{88, 103, 117}
\definecolor{coverline}{RGB}{190, 201, 210}
\definecolor{inlinecodeink}{RGB}{23, 74, 126}
\definecolor{codebg}{RGB}{246, 248, 250}
\definecolor{codeborder}{RGB}{198, 207, 216}

% ---- 高校论文风格字体规范（严格模式，不允许替代字体）----
% 英文与数字采用 Times 风格衬线字体；中文正文、标题和强调文本分别采用
% TeX Live 自带的宋体、黑体和楷体风格字体，保证本地与 CI 使用同一字体文件。
\setmainfont{__PDF_FONT_LATIN__}
\setmonofont{__PDF_FONT_CODE__}[Scale=MatchLowercase]
\setsansfont{__PDF_FONT_LATIN__}

% 中文正文使用宋体，标题和中文粗体使用黑体，中文斜体使用楷体。
% 字体缺失时由构建前检查直接报错，禁止静默回退。
\setCJKsansfont{__PDF_FONT_CJK_HEADING__}[BoldFont={__PDF_FONT_CJK_HEADING__}]
\setCJKmonofont{__PDF_FONT_CJK_BODY__}
\setCJKmainfont{__PDF_FONT_CJK_BODY__}[BoldFont={__PDF_FONT_CJK_HEADING__},ItalicFont={__PDF_FONT_CJK_EMPHASIS__}]

% ---- 中文断行与对齐优化 ----
\XeTeXlinebreaklocale "zh"
\XeTeXlinebreakskip = 0pt plus 1pt
\XeTeXlinebreakpenalty = 100

% ---- Word 默认 1.15 倍行距 ----
\setstretch{1.15}

% ---- 段间距：段后 8pt（Word 默认），首行缩进 2 字符 ----
\setlength{\parskip}{0.55em plus 0.15em minus 0.08em}
\setlength{\parindent}{2em}

% ---- 表格行距收紧，贴近 Word 默认 ----
\renewcommand{\arraystretch}{1.18}
\setlength{\tabcolsep}{5pt}

% ---- Word 风格版面稳定性：避免孤行、寡行和长英文溢出 ----
\widowpenalty=10000
\clubpenalty=10000
\displaywidowpenalty=10000
\brokenpenalty=10000
\setlength{\emergencystretch}{2em}
\raggedbottom

% 行内代码中的连字符默认不可断行；保留连字符并在其后提供明确断点。
\protected\def\sphinxhyphenininlineliteral#1{\discretionary{-}{}{-}}

% 行内代码沿用正文大小和配置的 Times 风格字体（中文按 CJK 正文映射为宋体），
% 只用颜色突出，不使用等宽字体或不可换行的彩色盒子。
\protected\def\sphinxcode#1{{\rmfamily\color{inlinecodeink}#1}}
\protected\def\sphinxbfcode#1{{\bfseries\sphinxcode{#1}}}

% 代码块采用克制的网页文档式灰底细边框；禁用 Pygments 的多色标记，
% 保留等宽代码字体和语法结构，避免页面出现高饱和色块。
\sphinxsetup{%
  pre_background-TeXcolor=codebg,
  pre_border-TeXcolor=codeborder,
  pre_border-width=0.45pt,
  pre_padding-top=6pt,
  pre_padding-right=7pt,
  pre_padding-bottom=6pt,
  pre_padding-left=7pt,
  pre_border-radius=1pt,
  pre_box-shadow=none,
  verbatimwrapslines=true,
  % 长代码行继续自动换行，但不在成品中显示可视空格和箭头提示。
  verbatimvisiblespace={},
  verbatimcontinued={\hspace{1.25em}}%
}
% fenced code blocks use one standard LaTeX size below the body text.
% Match the code font's x-height to the prose before stepping down one size.
% Inline code remains at the body size through \sphinxcode above.
\fvset{fontsize=\small,baselinestretch=1.08}

# 每篇正文文档从 section 开始，便于将目录 README 标题作为一级书签，
# 文档标题作为二级书签，文档内部章节作为三级书签。
\makeatletter
\def\PYG@tok#1{\let\PYG@bf\relax\let\PYG@it\relax\def\PYG@tc##1{##1}}
\makeatother

% 页面页眉只保留产品名；页脚不显示章节标题，仅保留居中页码。
\fancypagestyle{pdfnormal}{%
  \fancyhf{}%
  \fancyhead[L]{\rmfamily\small\bfseries \pdfheadertitle}%
  \fancyfoot[C]{\raisebox{4pt}{\rmfamily\small\thepage}}%
  \renewcommand{\headrulewidth}{0.4pt}%
  \renewcommand{\footrulewidth}{0pt}%
}
% 封面保留简洁版式，只显示页脚页码，不引入产品页眉。
\fancypagestyle{pdfcover}{%
  \fancyhf{}%
  \fancyfoot[C]{\raisebox{4pt}{\rmfamily\small\thepage}}%
  \renewcommand{\headrulewidth}{0pt}%
  \renewcommand{\footrulewidth}{0pt}%
}
\makeatletter
\let\ps@normal\ps@pdfnormal
\let\ps@plain\ps@pdfnormal
\newcommand{\pdfapplypagestyles}{%
  \let\ps@normal\ps@pdfnormal
  \let\ps@plain\ps@pdfnormal
}
\makeatother
\AtBeginDocument{\pdfapplypagestyles}
% Sphinx may register its plain style from a begin-document hook; bind both
% styles again after those hooks so even-numbered TOC pages keep the footer.

% ---- PDF 目录分类行：仅保留 README 标题，不生成分类正文页 ----
% 分类标题同时写入 PDF 纸面目录和书签，并跳转到该目录第一篇正文。
\newcommand{\pdfcategorytoc}[2]{%
  \Needspace{8\baselineskip}%
  \addvspace{0.75em}%
  \noindent{\sffamily\normalsize\bfseries\color{coverink}\hyperlink{#2}{#1}}\par
  \nopagebreak[4]\vspace{0.05em}%
}
\newcommand{\pdfcategoryanchor}[2]{%
  \phantomsection%
  % Reset document numbering at each directory README anchor.
  \setcounter{section}{0}%
  % Section counters restart for each directory, so give Hyperref a unique
  % destination namespace or every repeated section.0.1 target resolves to
  % the first document in the PDF.
  \gdef\pdfsectiongroup{#1}%
  % 独立锚点用于纸面目录链接，独立书签 ID 避免 hyperref 重命名目标。
  \hypertarget{#1}{}%
  \pdfbookmark[0]{#2}{pdf-bookmark-#1}%
  % Keep the directory README title in the body as the visible level-one
  % heading while omitting the README navigation prose itself.
  \Needspace{5\baselineskip}%
  \addvspace{0.8em}%
  \noindent{{\sffamily\fontsize{20pt}{28pt}\selectfont\bfseries\color{black}#2}}\par
  \vspace{0.8em}%
}
% The visible section numbers intentionally restart per directory; the hidden
% Hyperref numbers must remain globally unique for bookmarks and cross-links.
\providecommand{\pdfsectiongroup}{pdf-root}
\renewcommand{\theHsection}{pdfsection.\pdfsectiongroup.\arabic{section}}
\renewcommand{\theHsubsection}{\theHsection.\arabic{subsection}}
\renewcommand{\theHsubsubsection}{\theHsubsection.\arabic{subsubsection}}
% PDF 阶段剥离手工编号，再统一编号到三级标题。
\setcounter{secnumdepth}{2}
% ---- 章节标题层级：字号与粗细参照 Word Heading 1/2/3 ----
\usepackage{titlesec}
\titleformat{\section}
  {\sffamily\Large\bfseries\color{black}}
  {\thesection}{1em}{}
\titleformat{\subsection}
  {\sffamily\large\bfseries\color{black}}
  {\thesubsection}{1em}{}
\titleformat{\subsubsection}
  {\sffamily\normalsize\bfseries\color{black}}
  {\thesubsubsection}{1em}{}
\titlespacing*{\section}{0pt}{18pt plus 2pt minus 1pt}{6pt plus 1pt}
\titlespacing*{\subsection}{0pt}{14pt plus 2pt minus 1pt}{4pt plus 1pt}
\titlespacing*{\subsubsection}{0pt}{10pt plus 1pt minus 1pt}{2pt plus 1pt}
% Avoid 0.1-style numbers caused by the intentionally omitted chapter level.
% Documents start at 1; their internal headings use 1.1, 1.2, and so on.
\renewcommand{\thesection}{\arabic{section}.}
\renewcommand{\thesubsection}{\arabic{section}.\arabic{subsection}}
\renewcommand{\thesubsubsection}{\thesubsection.\arabic{subsubsection}}

% ---- 列表项之间留出 Word 风格的呼吸空间 ----
\usepackage{enumitem}
\setlist[itemize]{itemsep=2pt, parsep=2pt, topsep=2pt}
\setlist[enumerate]{itemsep=2pt, parsep=2pt, topsep=2pt}
''',
}

# The preamble is a raw LaTeX string; normalize any accidental Python-style
# comment lines so they cannot be interpreted as TeX macro parameters.
latex_elements['preamble'] = '\n'.join(
    ('%' + line[1:]) if line.startswith('#') else line
    for line in latex_elements['preamble'].split('\n')
)

for _placeholder, _font_name in {
    '__PDF_FONT_LATIN__': _latex_escape(pdf_font_latin),
    '__PDF_FONT_CODE__': _latex_escape(pdf_font_code),
    '__PDF_FONT_CJK_BODY__': _latex_escape(pdf_font_cjk_body),
    '__PDF_FONT_CJK_HEADING__': _latex_escape(pdf_font_cjk_heading),
    '__PDF_FONT_CJK_EMPHASIS__': _latex_escape(pdf_font_cjk_emphasis),
}.items():
    latex_elements['preamble'] = latex_elements['preamble'].replace(
        _placeholder, _font_name
    )

# Each body document starts at the LaTeX section level so that the directory
# README title can remain the top-level PDF bookmark and the document title
# becomes the second level.
latex_toplevel_sectioning = 'section'

pdf_chapter_label = (
    r'第\,\thechapter\,章'
    if pdf_is_chinese
    else r'CHAPTER \thechapter'
)
latex_elements['preamble'] += rf'''
% 产品名页眉由配置中的项目名生成，不携带版本号或章节标题。
\def\pdfheadertitle{{{_latex_escape(pdf_header_title)}}}
% ---- 章标题：替换 fncychap 的英文固定标签，并保持中英文构建一致 ----
\titleformat{{\chapter}}[display]
  {{\sffamily\bfseries\color{{black}}}}
  {{\filleft\Large {pdf_chapter_label}}}
  {{0.8em}}
  {{\titlerule\vspace{{0.8em}}\filleft\Huge}}
\titlespacing*{{\chapter}}{{0pt}}{{-0.6cm}}{{1.2cm}}
'''

if pdf_thesis_style:
    # 中国研究生论文常用版式：小四（12pt）正文、1.5 倍行距、首行缩进，
    # 段落之间不额外留空；左侧预留装订边，目录使用同等基线网格。
    latex_elements['pointsize'] = '12pt'
    latex_elements['preamble'] += r'''
% ---- 中国研究生论文预览样式（由 PDF_STYLE=thesis 启用）----
\geometry{a4paper, top=2.54cm, bottom=2.54cm, left=3.00cm, right=2.50cm,
          headheight=14pt, footskip=24pt, includehead=true, includefoot=true}
\usepackage{etoolbox}
\setstretch{1.5}
\setlength{\parskip}{0pt}
\setlength{\parindent}{2em}
\renewcommand{\arraystretch}{1.25}
\setlength{\tabcolsep}{6pt}
\fvset{fontsize=\small,baselinestretch=1.15}
\AtBeginEnvironment{tabularx}{\setstretch{1.15}}
\AtBeginEnvironment{sphinxVerbatim}{\small\setstretch{1.15}}
% 标题后需要承接正文或代码时，避免标题孤立在页尾造成大片空白。
\pretocmd{\section}{\Needspace{12\baselineskip}}{}{}
\pretocmd{\subsection}{\Needspace{7\baselineskip}}{}{}
\pretocmd{\subsubsection}{\Needspace{5\baselineskip}}{}{}
\renewcommand{\pdfcategorytoc}[2]{%
  \Needspace{3\baselineskip}%
  \addvspace{0.65em}%
  \noindent{\sffamily\bfseries\fontsize{12pt}{18pt}\selectfont
    \color{coverink}\hyperlink{#2}{#1}}\par
  \nopagebreak[4]\vspace{0.05em}%
}
\titleformat{\chapter}[display]
  {\sffamily\bfseries\centering\color{black}}
  {\fontsize{14pt}{21pt}\selectfont 第\,\thechapter\,章}
  {0.6em}
  {\fontsize{16pt}{24pt}\selectfont}
\titlespacing*{\chapter}{0pt}{0pt}{18pt}
\titleformat{\section}
  {\sffamily\bfseries\fontsize{14pt}{21pt}\selectfont\color{black}}
  {\thesection}{1em}{}
\titleformat{\subsection}
  {\sffamily\bfseries\fontsize{12pt}{18pt}\selectfont\color{black}}
  {\thesubsection}{1em}{}
\titleformat{\subsubsection}
  {\sffamily\bfseries\fontsize{12pt}{18pt}\selectfont\color{black}}
  {\thesubsubsection}{1em}{}
\titlespacing*{\section}{0pt}{18pt plus 2pt minus 1pt}{8pt}
\titlespacing*{\subsection}{0pt}{14pt plus 2pt minus 1pt}{6pt}
\titlespacing*{\subsubsection}{0pt}{10pt plus 1pt minus 1pt}{4pt}
\setlist[itemize]{itemsep=0.25em,parsep=0pt,topsep=0.5em}
\setlist[enumerate]{itemsep=0.25em,parsep=0pt,topsep=0.5em}
'''
    latex_elements['tableofcontents'] = rf'''
\clearpage
\renewcommand{{\contentsname}}{{{_latex_escape(pdf_contents_title)}}}
\pagestyle{{pdfnormal}}
\thispagestyle{{pdfnormal}}
\begingroup
\setlength{{\parskip}}{{0pt}}
\fontsize{{12pt}}{{18pt}}\selectfont
\sphinxtableofcontents
\endgroup
\clearpage
'''

# --- 国际 Word 排版补丁 (end) ---
