name: Build Documentation

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'docs/**'
      - '.github/versions.json'
      - 'projects/**'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/versions.json'
      - 'projects/**'
  workflow_dispatch:

jobs:
  validate-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd docs/source
          pip install -r requirements.txt

      - name: Validate version configuration
        run: |
          cd docs/source
          python utils/version_utils.py --validate

  build-docs:
    needs: validate-versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd docs/source
          pip install -r requirements.txt

      - name: Setup Google Chrome for headless PDF
        uses: browser-actions/setup-chrome@v1

      - name: Install Chinese fonts for PDF rendering
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            fonts-noto-cjk fonts-wqy-zenhei fonts-wqy-microhei \
            fonts-arphic-uming fonts-arphic-ukai
          sudo fc-cache -f -v || true

      - name: List version configurations
        run: |
          cd docs/source
          echo "=== 版本配置列表 ==="
          python utils/version_utils.py --list

      - name: Build all versions
        env:
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
          CHROME_PATH: ${{ env.CHROME_PATH }}
        run: |
          cd docs/source
          python build_manager.py --clean

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs/source/source_build/html
          retention-days: 30

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - name: Download documentation artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build
          path: docs/source/source_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/source/source_build/html
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com' 