name: Deploy Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - master
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Set up environment
        run: |
          export LANG=C.UTF-8
          export LC_ALL=C.UTF-8
          
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('source/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r source/requirements.txt

      - name: Generate documentation
        run: |
          cd source
          python version_generator.py
          # 确保latest目录存在
          if [ ! -d "_build/html/latest" ]; then
            echo "警告: latest目录不存在，创建默认重定向"
            mkdir -p _build/html/latest
            echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=../"><title>重定向</title></head><body>正在跳转...</body></html>' > _build/html/latest/index.html
          fi
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: source/_build/html
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com' 